version: "3.8"
services:
  fishdex-api:
    image: ghcr.io/${REPO}:${TAG}
    build:
      context: .
      dockerfile: /FishDexAPI/Dockerfile
    container_name: fishdex-api
    ports:
      - "8080:8080"

